name: NyaaUtils
main: cat.nyaa.nyaautils.NyaaUtils
description: "Helper/utilities plugin for Nyaacat Minecraft Server"
version: ${version}
depend: [WorldEdit,Essentials,NyaaCore]
softdepend: [LockettePro,HamsterEcoHelper]
authors: [RecursiveG,Cylin,Librazy]
website: "https://github.com/NyaaCat/nyaautils"
api-version: 1.13
commands:
  nyaautils:
    description: The command for NyaaUtils
    aliases: nu
    permission: nu.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  nu.command:
    description: Base permission node for commands
    default: true
  nu.enchant:
    description: Permission node for self-serve enchanting
    default: true
  nu.show:
    description: Permission node for show item
    default: true
  nu.reload:
    description: Reload permission
    default: op
  nu.addenchsrc:
    description: Add item as enchantment source
    default: op
  nu.launch:

    description: Launch player into sky
    default: op
  nu.lootprotect:
    description: Toggle loot protect status
    default: true
  nu.dropprotect:
    description: Toggle drop protect status
    default: true
  nu.exhibition.set:
    description: Exhibition modification
    default: true
  nu.exhibition.unset:
    description: Exhibition modification
    default: true
  nu.exhibition.desc:
    description: Exhibition modification
    default: true
  nu.exhibition.forceUnset:
    description: Exhibition modification
    default: op
  nu.prefix:
    default: true
  nu.suffix:
    default: true
  nu.format:
    default: true
  nu.project:
    description: Set player velocity
    default: op
  nu.enchantinfo:
    default: true
  nu.addfuel:
    default: op
  nu.givefuel:
    default: op
  nu.elytratoggle:
    default: true
  nu.mailbox:
    description: Basic permission requied for mailbox
    default: true
  nu.mailadmin:
    description: Administrative commands for mailbox
    default: op
  nu.repair:
    description: Repair item
    default: true
  nu.addrepair:
    description: Add repairable item
    default: op
  nu.createtimer:
    description: Add and remove timer
    default: op
  nu.rename:
    description: Rename item
    default: op
  nu.rename.blacklist:
    description: Bypass blacklist in renaming item
    default: false
  nu.setlore:
    description: Set or append item lore
    default: op
  nu.setbook:
    description: Set book author, title or unsign book
    default: op
  nu.realm.info:
    description: View realm info
    default: true
  nu.realm.mute:
    description: mute and unmute realm notification
    default: true
  nu.realm.admin:
    description: Create and remove realm
    default: op
  nu.particles.player:
    description: Select particle set
    default: true
  nu.particles.editor:
    description: Create and remove particle set
    default: op
  nu.particles.admin:
    description: Create and remove particle set
    default: op
  nu.se.player:
    description: Edit sign in your hand
    default: true
  nu.se.admin:
    description: Edit a sign
    default: op
  nu.expcap.store:
    description: Store experience
    default: true
  nu.expcap.restore:
    description: Restore experience
    default: true
  nu.expcap.set:
    description: Modify exp capsule
    default: op
  nu.vote:
    description: Start a vote
    default: true
  nu.redstonecontrol:
    description: Control redstone stuff by right click
    default: true
  nu.redstonecontrol.lamp:
    description: Light/off redstone lamp
    default: true
  nu.redstonecontrol.torch:
    description: Light/off redstone torch
    default: op
  nu.redstonecontrol.wire:
    description: Cycle through each level of power for redstone wire
    default: op
  nu.tps:
    description: Show TPS graph
    default: true
  nu.tps.verbose:
    description: Show TPS statics
    default: op
  nu.tps.tick:
    description: Show tick time record
    default: op
  nu.ping:
    description: Show player's ping
    default: true
  nu.ping.top:
    description: Show players' ping
    default: op
  nu.ping.others:
    description: Show other player's ping
    default: op
  nu.sit:
    description: allow player sit on blocks
    default: true
  nu.tpall:
    description: teleport all players to you
    default: op
  nu.bp.use:
    description: use extra backpack
    default: op
  nu.bp.admin:
    description: admin extra backpack
    default: op
